server:
  #port: 8081
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: ms-venta-service

  jpa:
    hibernate:
      ddl-auto: update  # Esto puede ser 'create', 'validate', etc., dependiendo de tu necesidad
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_venta  # URL de conexión a MySQL
    username: root  # Cambia esto por el nombre de usuario de tu base de datos MySQL
    password:

  h2:
    console:
      enabled: false  # Deshabilitamos la consola H2 ya que no la estamos usando

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    pedidoServiceCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
    clientServiceCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
